

services:
  redis:
    image: redis:alpine

  backend:
    image: example-backend 
    environment:
      - REQUEST_ORIGIN=http://localhost:5001
      - REDIS_HOST=redis
    ports:
      - "8081:8080"
    restart: unless-stopped

  frontend:
    image: example-frontend
    ports:
      - "5001:5000"

 



    