services:
  backend:
    image: example-backend 
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://localhost:5001
    ports:
      - "8081:8080"

  frontend:
    image: example-frontend 
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8081
    ports:
      - "5001:5000"
    depends_on:
      - backend