services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
  redis:
    image: redis:alpine
  backend:
    image: example-backend 
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=db
    restart: unless-stopped
    depends_on:
      - db
  frontend:
    image: example-frontend
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_postgres
    volumes:
      - ./database:/var/lib/postgresql/data