services:
  redis:
    image: redis:alpine

  backend:
    image: example-backend 
    environment:
      - REQUEST_ORIGIN=http://localhost:5001
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=db
    ports:
      - "8081:8080"
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    image: example-frontend
    ports:
      - "5001:5000"

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_postgres
    volumes:
      - ./database:/var/lib/postgresql/data

       